final wordTheme = [
  {"value": 0, "label": "TOUS"},
  {"value": 1, "label": "L'ÉCOLE – LA CLASSE – L'INSTRUCTION"},
  {"value": 2, "label": "PAYSAGES – CLIMAT – FORMES"},
  {"value": 3, "label": "QUALITÉS ET DÉFAUTS"},
  {"value": 4, "label": "CALCUL ET MESURES"},
  {"value": 5, "label": "LES ALIMENTS – LES BOISSONS- LES REPAS"},
  {"value": 6, "label": "LE CORPS HUMAIN"},
  {"value": 7, "label": "LES SENS – LA VOLONTE – L'INTELLIGENCE"},
  {"value": 8, "label": "L'INTÉRIEUR ET LE MOBILIER"},
  {"value": 9, "label": "L'INDUSTRIE ET LE TRAVAIL"},
  {"value": 10, "label": "LES ARTS"},
  {"value": 11, "label": "L'AGRICULTURE"},
  {"value": 12, "label": "VERGER – BOIS – CHASSE - PÊCHE"},
  {"value": 13, "label": "GESTES ET MOUVEMENTS"},
  {"value": 14, "label": "ÉPOQUE – TEMPS - SAISONS"},
  {"value": 15, "label": "VÊTEMENTS – TOILETTE - PARURES"},
  {"value": 16, "label": "SPORTS ET JEUX"},
  {"value": 17, "label": "LA MAISON – LE BATIMENT"},
  {"value": 18, "label": "LES VOYAGES"},
  {"value": 19, "label": "LES ANIMAUX"},
  {"value": 20, "label": "VILLE – VILLAGE – UNIVERS - DIMENSIONS"},
  {"value": 21, "label": "EAUX – MINÉRAUX - VÉGÉTAUX"},
  {"value": 22, "label": "LE COMMERCE"},
  {"value": 23, "label": "LA COMMUNICATION"},
  {"value": 24, "label": "JOIES ET PEINES"},
  {"value": 25, "label": "GOUVERNEMENT ET JUSTICE"},
  {"value": 26, "label": "L'ARMÉE"},
  {"value": 27, "label": "VIE HUMAINE – MALADIES - HYGIÈNE"},
];
